## Exemplo1

In [1]:
# Exemplo de Cramer
import numpy as np
#cria a matriz incompleta
matriz_D=np.matrix([[1,1,1],[1,-1,-1],[2,-1,1]])
#calcula o determinante de D
D=np.linalg.det(matriz_D)
print(round(D,2))
#cria a matriz Dx
matriz_Dx=np.matrix([[6,1,1],[-4,-1,-1],[1,-1,1]])
Dx=np.linalg.det(matriz_Dx)
#cria a matriz Dy
matriz_Dy=np.matrix([[1,6,1],[1,-4,-1],[2,1,1]])
Dy=np.linalg.det(matriz_Dy)
#cria a matriz Dz
matriz_Dz=np.matrix([[1,1,6],[1,-1,-4],[2,-1,1]])
Dz=np.linalg.det(matriz_Dz)
x=Dx/D
y=Dy/D
z=Dz/D
print("x=",np.round(x,2))
print("y=",np.round(y,2))
print("z=", np.round(z,2))

-4.0
x= 1.0
y= 3.0
z= 2.0


## Exemplo 2

In [3]:
# Resolução de Sistemas Lineares

# Eliminação de Gauss

import numpy as np
x=[]

def gaussElimin(C,n,m):
    for k in range (0,n):
        if C[k,k]==0:
            for s in range (k+1,n):
                if C[s,k]!=0:
                    aux=C[k,:]
                    C[k,:]=C[s,:]
                    C[s,:]=aux
        for i in range (k+1,n):
            mik=C[i,k]/C[k,k]
            for j in range (k,m):
                C[i,j]=C[i,j]-mik*C[k,j] 
                      
    return C

A=np.array([[1,-1,1,4],[3,2,1,0],[5,5,1,-4]])
#transfoma em float
A=A.astype(float)
n = len(A)
m = len(A[0])
X= gaussElimin(A,n,m)
if X[n-1,m-2]==0 and X[n-1,m-1]==0:
    print('o sistema é indeterminado')
elif X[n-1,m-2]==0 and [n-1,m-1]!=0:
    print('o sistema é impossível')
else:
    x = n*[0]
    for i in range(n-1, -1, -1):
        s = sum([A[i][j]*x[j]for j in range(i+1,n)])
        x[i] = (A[i][n] - s)/A[i][i]
    print(x)

o sistema é indeterminado


## Exemplo 3

In [4]:
#Importa biblioteca numpy que permite trabalhar com matrizes
#Função matrix para definir matrizes
#função linalg para fazer matiz inversa
import numpy as np
#cria a matriz A
matriz_A=np.matrix([[6,2,-1],[2,4,1],[3,2,8]])
#cria a matriz B
matriz_B=([[7],[7],[13]])
#cria a matriz inversa de A
matriz_A_inv=np.linalg.inv(matriz_A)
#Resolve o sistema linear
sol=matriz_A_inv*matriz_B
print("Resultado do sistema linear")
print(sol)

Resultado do sistema linear
[[1.]
 [1.]
 [1.]]


## Exemplo 4

In [5]:
#Resolve com solve
import numpy as np
#cria a matriz A
matriz_A=np.matrix([[6,2,-1],[2,4,1],[3,2,8]])
#cria a matriz B
matriz_B=([[7],[7],[13]])
sol=np.linalg.solve(matriz_A,matriz_B)
print(sol)

[[1.]
 [1.]
 [1.]]


## Exemplo 5

In [6]:
from sympy import Matrix, solve_linear_system
from sympy.abc import x, y,z
system = Matrix(( (8,-4,-2,10), (-4,10,-2,0),(-2,-2,10,4)))
solve_linear_system(system, x, y,z)

{x: 2, y: 1, z: 1}

## Exemplo 6

In [7]:
from sympy import Matrix, solve_linear_system
from sympy.abc import x, y,z
system = Matrix(( (1,-1,1,4), (3,2,1,0),(5,5,1,-4)))
solve_linear_system(system, x, y,z)

{y: 2*z/5 - 12/5, x: 8/5 - 3*z/5}

In [4]:
#Resolve com solve
import numpy as np
#cria a matriz A
matriz_A=np.matrix([[1,-1,1],[3,2,1],[5,5,1]])
#cria a matriz B
matriz_B=([[4],[0],[-4]])
sol=np.linalg.solve(matriz_A,matriz_B)
print(sol)
D=np.linalg.det(matriz_A)
print(D)

[[ 0.30769231]
 [-1.53846154]
 [ 2.15384615]]
2.8865798640253924e-15


In [2]:
from sympy import Matrix, solve_linear_system
from sympy.abc import x, y,z
system = Matrix(( (1,-1,1,4), (3,2,1,0),(5,5,1,-4)))
solve_linear_system(system, x, y,z)

{y: 2*z/5 - 12/5, x: 8/5 - 3*z/5}